include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "build/**"
    - "lib/**/*.g.dart"
    - "lib/**/*.freezed.dart"
    - "test/**/*.g.dart"
    - "test/**/*.freezed.dart"
    - tool/**
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    # Stylistic
    - always_declare_return_types
    - annotate_overrides
    - avoid_init_to_null
    - avoid_null_checks_in_equality_operators
    - avoid_print # Use Loggers
    - avoid_renaming_method_parameters
    - avoid_return_types_on_setters
    - avoid_shadowing_type_parameters
    - avoid_single_cascade_in_expression_statements
    - avoid_unnecessary_containers
    - await_only_futures
    - camel_case_types
    - cancel_subscriptions
    - constant_identifier_names
    - control_flow_in_finally
    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    - exhaustive_cases
    - file_names
    - library_names
    - library_prefixes
    - no_duplicate_case_values
    - null_closures
    - package_names
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_contains
    - prefer_equal_for_default_values
    - prefer_final_fields
    - prefer_final_locals
    - prefer_if_null_operators
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_iterable_whereType
    - prefer_single_quotes
    - prefer_spread_collections
    - recursive_getters
    - slash_for_doc_comments
    - type_init_formals
    - unawaited_futures
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_new
    - unnecessary_null_in_if_null_operators
    - unnecessary_this
    - unrelated_type_equality_checks
    - use_function_type_syntax_for_parameters
    - use_rethrow_when_possible
    - valid_regexps
    # Safety & Design Discipline
    - use_build_context_synchronously
    - avoid_function_literals_in_foreach_calls
    - prefer_const_literals_to_create_immutables
