// Mocks generated by Mockito 5.4.6 from annotations
// in mube/test/integration/search/search_flow_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:cloud_firestore/cloud_firestore.dart' as _i11;
import 'package:firebase_auth/firebase_auth.dart' as _i4;
import 'package:flutter/foundation.dart' as _i12;
import 'package:fpdart/fpdart.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i13;
import 'package:mube/src/core/errors/failures.dart' as _i8;
import 'package:mube/src/features/auth/data/auth_remote_data_source.dart'
    as _i2;
import 'package:mube/src/features/auth/domain/app_user.dart' as _i5;
import 'package:mube/src/features/feed/domain/feed_item.dart' as _i9;
import 'package:mube/src/features/search/data/search_repository.dart' as _i6;
import 'package:mube/src/features/search/domain/search_filters.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i2.AuthRemoteDataSource {
  @override
  _i3.Stream<_i4.User?> authStateChanges() =>
      (super.noSuchMethod(
            Invocation.method(#authStateChanges, []),
            returnValue: _i3.Stream<_i4.User?>.empty(),
            returnValueForMissingStub: _i3.Stream<_i4.User?>.empty(),
          )
          as _i3.Stream<_i4.User?>);

  @override
  _i3.Future<void> signInWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailAndPassword, [email, password]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.User?> registerWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#registerWithEmailAndPassword, [email, password]),
            returnValue: _i3.Future<_i4.User?>.value(),
            returnValueForMissingStub: _i3.Future<_i4.User?>.value(),
          )
          as _i3.Future<_i4.User?>);

  @override
  _i3.Future<void> saveUserProfile(_i5.AppUser? user) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserProfile, [user]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateUserProfile(_i5.AppUser? user) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfile, [user]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i5.AppUser?> fetchUserProfile(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUserProfile, [uid]),
            returnValue: _i3.Future<_i5.AppUser?>.value(),
            returnValueForMissingStub: _i3.Future<_i5.AppUser?>.value(),
          )
          as _i3.Future<_i5.AppUser?>);

  @override
  _i3.Stream<_i5.AppUser?> watchUserProfile(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#watchUserProfile, [uid]),
            returnValue: _i3.Stream<_i5.AppUser?>.empty(),
            returnValueForMissingStub: _i3.Stream<_i5.AppUser?>.empty(),
          )
          as _i3.Stream<_i5.AppUser?>);

  @override
  _i3.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteAccount(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, [uid]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.AppUser>> fetchUsersByIds(List<String>? uids) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUsersByIds, [uids]),
            returnValue: _i3.Future<List<_i5.AppUser>>.value(<_i5.AppUser>[]),
            returnValueForMissingStub: _i3.Future<List<_i5.AppUser>>.value(
              <_i5.AppUser>[],
            ),
          )
          as _i3.Future<List<_i5.AppUser>>);

  @override
  _i3.Future<void> sendPasswordResetEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [email]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> sendEmailVerification() =>
      (super.noSuchMethod(
            Invocation.method(#sendEmailVerification, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> isEmailVerified() =>
      (super.noSuchMethod(
            Invocation.method(#isEmailVerified, []),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> reloadUser() =>
      (super.noSuchMethod(
            Invocation.method(#reloadUser, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [SearchRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchRepository extends _i1.Mock implements _i6.SearchRepository {
  @override
  _i3.Future<_i7.Either<_i8.Failure, List<_i9.FeedItem>>> searchUsers({
    required _i10.SearchFilters? filters,
    _i11.DocumentSnapshot<Object?>? startAfter,
    required int? requestId,
    required _i12.ValueGetter<int>? getCurrentRequestId,
    List<String>? blockedUsers = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchUsers, [], {
              #filters: filters,
              #startAfter: startAfter,
              #requestId: requestId,
              #getCurrentRequestId: getCurrentRequestId,
              #blockedUsers: blockedUsers,
            }),
            returnValue:
                _i3.Future<_i7.Either<_i8.Failure, List<_i9.FeedItem>>>.value(
                  _i13.dummyValue<_i7.Either<_i8.Failure, List<_i9.FeedItem>>>(
                    this,
                    Invocation.method(#searchUsers, [], {
                      #filters: filters,
                      #startAfter: startAfter,
                      #requestId: requestId,
                      #getCurrentRequestId: getCurrentRequestId,
                      #blockedUsers: blockedUsers,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i7.Either<_i8.Failure, List<_i9.FeedItem>>>.value(
                  _i13.dummyValue<_i7.Either<_i8.Failure, List<_i9.FeedItem>>>(
                    this,
                    Invocation.method(#searchUsers, [], {
                      #filters: filters,
                      #startAfter: startAfter,
                      #requestId: requestId,
                      #getCurrentRequestId: getCurrentRequestId,
                      #blockedUsers: blockedUsers,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i7.Either<_i8.Failure, List<_i9.FeedItem>>>);
}
