// Mocks generated by Mockito 5.4.6 from annotations
// in mube/test/unit/auth/profile_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i11;

import 'package:firebase_auth/firebase_auth.dart' as _i6;
import 'package:flutter/widgets.dart' as _i3;
import 'package:fpdart/fpdart.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:mube/src/core/errors/failures.dart' as _i8;
import 'package:mube/src/core/services/analytics/analytics_service.dart'
    as _i13;
import 'package:mube/src/features/auth/data/auth_repository.dart' as _i4;
import 'package:mube/src/features/auth/domain/app_user.dart' as _i10;
import 'package:mube/src/features/storage/data/storage_repository.dart' as _i2;
import 'package:mube/src/shared/services/content_moderation_service.dart'
    as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeImageUrls_0 extends _i1.SmartFake implements _i2.ImageUrls {
  _FakeImageUrls_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGalleryMediaUrls_1 extends _i1.SmartFake
    implements _i2.GalleryMediaUrls {
  _FakeGalleryMediaUrls_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNavigatorObserver_2 extends _i1.SmartFake
    implements _i3.NavigatorObserver {
  _FakeNavigatorObserver_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i4.AuthRepository {
  @override
  bool get isCurrentUserEmailVerified =>
      (super.noSuchMethod(
            Invocation.getter(#isCurrentUserEmailVerified),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.Stream<_i6.User?> authStateChanges() =>
      (super.noSuchMethod(
            Invocation.method(#authStateChanges, []),
            returnValue: _i5.Stream<_i6.User?>.empty(),
            returnValueForMissingStub: _i5.Stream<_i6.User?>.empty(),
          )
          as _i5.Stream<_i6.User?>);

  @override
  _i5.Future<_i7.Either<_i8.Failure, _i7.Unit>> signInWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailAndPassword, [email, password]),
            returnValue: _i5.Future<_i7.Either<_i8.Failure, _i7.Unit>>.value(
              _i9.dummyValue<_i7.Either<_i8.Failure, _i7.Unit>>(
                this,
                Invocation.method(#signInWithEmailAndPassword, [
                  email,
                  password,
                ]),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i7.Either<_i8.Failure, _i7.Unit>>.value(
                  _i9.dummyValue<_i7.Either<_i8.Failure, _i7.Unit>>(
                    this,
                    Invocation.method(#signInWithEmailAndPassword, [
                      email,
                      password,
                    ]),
                  ),
                ),
          )
          as _i5.Future<_i7.Either<_i8.Failure, _i7.Unit>>);

  @override
  _i5.Future<_i7.Either<_i8.Failure, _i7.Unit>> registerWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registerWithEmailAndPassword, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i5.Future<_i7.Either<_i8.Failure, _i7.Unit>>.value(
              _i9.dummyValue<_i7.Either<_i8.Failure, _i7.Unit>>(
                this,
                Invocation.method(#registerWithEmailAndPassword, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i7.Either<_i8.Failure, _i7.Unit>>.value(
                  _i9.dummyValue<_i7.Either<_i8.Failure, _i7.Unit>>(
                    this,
                    Invocation.method(#registerWithEmailAndPassword, [], {
                      #email: email,
                      #password: password,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i7.Either<_i8.Failure, _i7.Unit>>);

  @override
  _i5.Future<_i7.Either<_i8.Failure, _i7.Unit>> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i5.Future<_i7.Either<_i8.Failure, _i7.Unit>>.value(
              _i9.dummyValue<_i7.Either<_i8.Failure, _i7.Unit>>(
                this,
                Invocation.method(#signOut, []),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i7.Either<_i8.Failure, _i7.Unit>>.value(
                  _i9.dummyValue<_i7.Either<_i8.Failure, _i7.Unit>>(
                    this,
                    Invocation.method(#signOut, []),
                  ),
                ),
          )
          as _i5.Future<_i7.Either<_i8.Failure, _i7.Unit>>);

  @override
  _i5.Stream<_i10.AppUser?> watchUser(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#watchUser, [uid]),
            returnValue: _i5.Stream<_i10.AppUser?>.empty(),
            returnValueForMissingStub: _i5.Stream<_i10.AppUser?>.empty(),
          )
          as _i5.Stream<_i10.AppUser?>);

  @override
  _i5.Future<_i7.Either<_i8.Failure, _i7.Unit>> updateUser(
    _i10.AppUser? user,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [user]),
            returnValue: _i5.Future<_i7.Either<_i8.Failure, _i7.Unit>>.value(
              _i9.dummyValue<_i7.Either<_i8.Failure, _i7.Unit>>(
                this,
                Invocation.method(#updateUser, [user]),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i7.Either<_i8.Failure, _i7.Unit>>.value(
                  _i9.dummyValue<_i7.Either<_i8.Failure, _i7.Unit>>(
                    this,
                    Invocation.method(#updateUser, [user]),
                  ),
                ),
          )
          as _i5.Future<_i7.Either<_i8.Failure, _i7.Unit>>);

  @override
  _i5.Future<_i7.Either<_i8.Failure, _i7.Unit>> deleteAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, []),
            returnValue: _i5.Future<_i7.Either<_i8.Failure, _i7.Unit>>.value(
              _i9.dummyValue<_i7.Either<_i8.Failure, _i7.Unit>>(
                this,
                Invocation.method(#deleteAccount, []),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i7.Either<_i8.Failure, _i7.Unit>>.value(
                  _i9.dummyValue<_i7.Either<_i8.Failure, _i7.Unit>>(
                    this,
                    Invocation.method(#deleteAccount, []),
                  ),
                ),
          )
          as _i5.Future<_i7.Either<_i8.Failure, _i7.Unit>>);

  @override
  _i5.Future<_i7.Either<_i8.Failure, List<_i10.AppUser>>> getUsersByIds(
    List<String>? uids,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUsersByIds, [uids]),
            returnValue:
                _i5.Future<_i7.Either<_i8.Failure, List<_i10.AppUser>>>.value(
                  _i9.dummyValue<_i7.Either<_i8.Failure, List<_i10.AppUser>>>(
                    this,
                    Invocation.method(#getUsersByIds, [uids]),
                  ),
                ),
            returnValueForMissingStub:
                _i5.Future<_i7.Either<_i8.Failure, List<_i10.AppUser>>>.value(
                  _i9.dummyValue<_i7.Either<_i8.Failure, List<_i10.AppUser>>>(
                    this,
                    Invocation.method(#getUsersByIds, [uids]),
                  ),
                ),
          )
          as _i5.Future<_i7.Either<_i8.Failure, List<_i10.AppUser>>>);

  @override
  _i5.Future<_i7.Either<_i8.Failure, _i7.Unit>> sendPasswordResetEmail(
    String? email,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [email]),
            returnValue: _i5.Future<_i7.Either<_i8.Failure, _i7.Unit>>.value(
              _i9.dummyValue<_i7.Either<_i8.Failure, _i7.Unit>>(
                this,
                Invocation.method(#sendPasswordResetEmail, [email]),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i7.Either<_i8.Failure, _i7.Unit>>.value(
                  _i9.dummyValue<_i7.Either<_i8.Failure, _i7.Unit>>(
                    this,
                    Invocation.method(#sendPasswordResetEmail, [email]),
                  ),
                ),
          )
          as _i5.Future<_i7.Either<_i8.Failure, _i7.Unit>>);

  @override
  _i5.Future<_i7.Either<_i8.Failure, _i7.Unit>> sendEmailVerification() =>
      (super.noSuchMethod(
            Invocation.method(#sendEmailVerification, []),
            returnValue: _i5.Future<_i7.Either<_i8.Failure, _i7.Unit>>.value(
              _i9.dummyValue<_i7.Either<_i8.Failure, _i7.Unit>>(
                this,
                Invocation.method(#sendEmailVerification, []),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i7.Either<_i8.Failure, _i7.Unit>>.value(
                  _i9.dummyValue<_i7.Either<_i8.Failure, _i7.Unit>>(
                    this,
                    Invocation.method(#sendEmailVerification, []),
                  ),
                ),
          )
          as _i5.Future<_i7.Either<_i8.Failure, _i7.Unit>>);

  @override
  _i5.Future<bool> isEmailVerified() =>
      (super.noSuchMethod(
            Invocation.method(#isEmailVerified, []),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> hasVerifiedEmailTokenClaim({bool? forceRefresh = false}) =>
      (super.noSuchMethod(
            Invocation.method(#hasVerifiedEmailTokenClaim, [], {
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> reloadUser() =>
      (super.noSuchMethod(
            Invocation.method(#reloadUser, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i7.Either<_i8.Failure, _i7.Unit>>
  ensureCurrentUserProfileExists() =>
      (super.noSuchMethod(
            Invocation.method(#ensureCurrentUserProfileExists, []),
            returnValue: _i5.Future<_i7.Either<_i8.Failure, _i7.Unit>>.value(
              _i9.dummyValue<_i7.Either<_i8.Failure, _i7.Unit>>(
                this,
                Invocation.method(#ensureCurrentUserProfileExists, []),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i7.Either<_i8.Failure, _i7.Unit>>.value(
                  _i9.dummyValue<_i7.Either<_i8.Failure, _i7.Unit>>(
                    this,
                    Invocation.method(#ensureCurrentUserProfileExists, []),
                  ),
                ),
          )
          as _i5.Future<_i7.Either<_i8.Failure, _i7.Unit>>);

  @override
  _i5.Future<_i7.Either<_i8.Failure, _i7.Unit>> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i5.Future<_i7.Either<_i8.Failure, _i7.Unit>>.value(
              _i9.dummyValue<_i7.Either<_i8.Failure, _i7.Unit>>(
                this,
                Invocation.method(#signInWithGoogle, []),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i7.Either<_i8.Failure, _i7.Unit>>.value(
                  _i9.dummyValue<_i7.Either<_i8.Failure, _i7.Unit>>(
                    this,
                    Invocation.method(#signInWithGoogle, []),
                  ),
                ),
          )
          as _i5.Future<_i7.Either<_i8.Failure, _i7.Unit>>);

  @override
  _i5.Future<_i7.Either<_i8.Failure, _i7.Unit>> signInWithApple() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithApple, []),
            returnValue: _i5.Future<_i7.Either<_i8.Failure, _i7.Unit>>.value(
              _i9.dummyValue<_i7.Either<_i8.Failure, _i7.Unit>>(
                this,
                Invocation.method(#signInWithApple, []),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i7.Either<_i8.Failure, _i7.Unit>>.value(
                  _i9.dummyValue<_i7.Either<_i8.Failure, _i7.Unit>>(
                    this,
                    Invocation.method(#signInWithApple, []),
                  ),
                ),
          )
          as _i5.Future<_i7.Either<_i8.Failure, _i7.Unit>>);
}

/// A class which mocks [StorageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageRepository extends _i1.Mock implements _i2.StorageRepository {
  @override
  _i5.Future<_i2.ImageUrls> uploadProfileImageWithSizes({
    required String? userId,
    required _i11.File? file,
    bool? generateMultipleSizes = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadProfileImageWithSizes, [], {
              #userId: userId,
              #file: file,
              #generateMultipleSizes: generateMultipleSizes,
            }),
            returnValue: _i5.Future<_i2.ImageUrls>.value(
              _FakeImageUrls_0(
                this,
                Invocation.method(#uploadProfileImageWithSizes, [], {
                  #userId: userId,
                  #file: file,
                  #generateMultipleSizes: generateMultipleSizes,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.ImageUrls>.value(
              _FakeImageUrls_0(
                this,
                Invocation.method(#uploadProfileImageWithSizes, [], {
                  #userId: userId,
                  #file: file,
                  #generateMultipleSizes: generateMultipleSizes,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.ImageUrls>);

  @override
  _i5.Future<String> uploadProfileImage({
    required String? userId,
    required _i11.File? file,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadProfileImage, [], {
              #userId: userId,
              #file: file,
            }),
            returnValue: _i5.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#uploadProfileImage, [], {
                  #userId: userId,
                  #file: file,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#uploadProfileImage, [], {
                  #userId: userId,
                  #file: file,
                }),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<_i2.GalleryMediaUrls> uploadGalleryMediaWithSizes({
    required String? userId,
    required _i11.File? file,
    required String? mediaId,
    required bool? isVideo,
    void Function(double)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadGalleryMediaWithSizes, [], {
              #userId: userId,
              #file: file,
              #mediaId: mediaId,
              #isVideo: isVideo,
              #onProgress: onProgress,
            }),
            returnValue: _i5.Future<_i2.GalleryMediaUrls>.value(
              _FakeGalleryMediaUrls_1(
                this,
                Invocation.method(#uploadGalleryMediaWithSizes, [], {
                  #userId: userId,
                  #file: file,
                  #mediaId: mediaId,
                  #isVideo: isVideo,
                  #onProgress: onProgress,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.GalleryMediaUrls>.value(
              _FakeGalleryMediaUrls_1(
                this,
                Invocation.method(#uploadGalleryMediaWithSizes, [], {
                  #userId: userId,
                  #file: file,
                  #mediaId: mediaId,
                  #isVideo: isVideo,
                  #onProgress: onProgress,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.GalleryMediaUrls>);

  @override
  _i5.Future<String> uploadGalleryMedia({
    required String? userId,
    required _i11.File? file,
    required String? mediaId,
    required bool? isVideo,
    void Function(double)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadGalleryMedia, [], {
              #userId: userId,
              #file: file,
              #mediaId: mediaId,
              #isVideo: isVideo,
              #onProgress: onProgress,
            }),
            returnValue: _i5.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#uploadGalleryMedia, [], {
                  #userId: userId,
                  #file: file,
                  #mediaId: mediaId,
                  #isVideo: isVideo,
                  #onProgress: onProgress,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#uploadGalleryMedia, [], {
                  #userId: userId,
                  #file: file,
                  #mediaId: mediaId,
                  #isVideo: isVideo,
                  #onProgress: onProgress,
                }),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<String> uploadVideoThumbnail({
    required String? userId,
    required String? mediaId,
    required _i11.File? thumbnail,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadVideoThumbnail, [], {
              #userId: userId,
              #mediaId: mediaId,
              #thumbnail: thumbnail,
            }),
            returnValue: _i5.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#uploadVideoThumbnail, [], {
                  #userId: userId,
                  #mediaId: mediaId,
                  #thumbnail: thumbnail,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#uploadVideoThumbnail, [], {
                  #userId: userId,
                  #mediaId: mediaId,
                  #thumbnail: thumbnail,
                }),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<void> deleteImage(String? imageUrl) =>
      (super.noSuchMethod(
            Invocation.method(#deleteImage, [imageUrl]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteGalleryItem({
    required String? userId,
    required String? mediaId,
    required bool? isVideo,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteGalleryItem, [], {
              #userId: userId,
              #mediaId: mediaId,
              #isVideo: isVideo,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteProfileImages(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProfileImages, [userId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String> uploadSupportAttachment({
    required String? ticketId,
    required _i11.File? file,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadSupportAttachment, [], {
              #ticketId: ticketId,
              #file: file,
            }),
            returnValue: _i5.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#uploadSupportAttachment, [], {
                  #ticketId: ticketId,
                  #file: file,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#uploadSupportAttachment, [], {
                  #ticketId: ticketId,
                  #file: file,
                }),
              ),
            ),
          )
          as _i5.Future<String>);
}

/// A class which mocks [ContentModerationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockContentModerationService extends _i1.Mock
    implements _i12.ContentModerationService {
  @override
  _i5.Future<bool> validateImage(_i11.File? imageFile) =>
      (super.noSuchMethod(
            Invocation.method(#validateImage, [imageFile]),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}

/// A class which mocks [AnalyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsService extends _i1.Mock implements _i13.AnalyticsService {
  @override
  _i5.Future<void> logEvent({
    required String? name,
    Map<String, Object>? parameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logEvent, [], {
              #name: name,
              #parameters: parameters,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> logScreenView({
    required String? screenName,
    String? screenClass,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logScreenView, [], {
              #screenName: screenName,
              #screenClass: screenClass,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setUserProperty({
    required String? name,
    required String? value,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setUserProperty, [], {
              #name: name,
              #value: value,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setUserId(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#setUserId, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i3.NavigatorObserver getObserver() =>
      (super.noSuchMethod(
            Invocation.method(#getObserver, []),
            returnValue: _FakeNavigatorObserver_2(
              this,
              Invocation.method(#getObserver, []),
            ),
            returnValueForMissingStub: _FakeNavigatorObserver_2(
              this,
              Invocation.method(#getObserver, []),
            ),
          )
          as _i3.NavigatorObserver);

  @override
  _i5.Future<void> logAuthSignupComplete({required String? method}) =>
      (super.noSuchMethod(
            Invocation.method(#logAuthSignupComplete, [], {#method: method}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> logMatchPointFilter({
    required List<String>? instruments,
    required List<String>? genres,
    required double? distance,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logMatchPointFilter, [], {
              #instruments: instruments,
              #genres: genres,
              #distance: distance,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> logFeedPostView({required String? postId}) =>
      (super.noSuchMethod(
            Invocation.method(#logFeedPostView, [], {#postId: postId}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> logProfileEdit({required String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#logProfileEdit, [], {#userId: userId}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
