// Mocks generated by Mockito 5.4.6 from annotations
// in mube/test/unit/auth/register_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:firebase_analytics/firebase_analytics.dart' as _i2;
import 'package:firebase_auth/firebase_auth.dart' as _i5;
import 'package:fpdart/fpdart.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:mube/src/core/errors/failures.dart' as _i7;
import 'package:mube/src/core/services/analytics/analytics_service.dart'
    as _i10;
import 'package:mube/src/features/auth/data/auth_repository.dart' as _i3;
import 'package:mube/src/features/auth/domain/app_user.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFirebaseAnalyticsObserver_0 extends _i1.SmartFake
    implements _i2.FirebaseAnalyticsObserver {
  _FakeFirebaseAnalyticsObserver_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  @override
  bool get isCurrentUserEmailVerified =>
      (super.noSuchMethod(
            Invocation.getter(#isCurrentUserEmailVerified),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.Stream<_i5.User?> authStateChanges() =>
      (super.noSuchMethod(
            Invocation.method(#authStateChanges, []),
            returnValue: _i4.Stream<_i5.User?>.empty(),
            returnValueForMissingStub: _i4.Stream<_i5.User?>.empty(),
          )
          as _i4.Stream<_i5.User?>);

  @override
  _i4.Future<_i6.Either<_i7.Failure, _i6.Unit>> signInWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailAndPassword, [email, password]),
            returnValue: _i4.Future<_i6.Either<_i7.Failure, _i6.Unit>>.value(
              _i8.dummyValue<_i6.Either<_i7.Failure, _i6.Unit>>(
                this,
                Invocation.method(#signInWithEmailAndPassword, [
                  email,
                  password,
                ]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i6.Either<_i7.Failure, _i6.Unit>>.value(
                  _i8.dummyValue<_i6.Either<_i7.Failure, _i6.Unit>>(
                    this,
                    Invocation.method(#signInWithEmailAndPassword, [
                      email,
                      password,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i6.Either<_i7.Failure, _i6.Unit>>);

  @override
  _i4.Future<_i6.Either<_i7.Failure, _i6.Unit>> registerWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registerWithEmailAndPassword, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i4.Future<_i6.Either<_i7.Failure, _i6.Unit>>.value(
              _i8.dummyValue<_i6.Either<_i7.Failure, _i6.Unit>>(
                this,
                Invocation.method(#registerWithEmailAndPassword, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i6.Either<_i7.Failure, _i6.Unit>>.value(
                  _i8.dummyValue<_i6.Either<_i7.Failure, _i6.Unit>>(
                    this,
                    Invocation.method(#registerWithEmailAndPassword, [], {
                      #email: email,
                      #password: password,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i6.Either<_i7.Failure, _i6.Unit>>);

  @override
  _i4.Future<_i6.Either<_i7.Failure, _i6.Unit>> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i4.Future<_i6.Either<_i7.Failure, _i6.Unit>>.value(
              _i8.dummyValue<_i6.Either<_i7.Failure, _i6.Unit>>(
                this,
                Invocation.method(#signOut, []),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i6.Either<_i7.Failure, _i6.Unit>>.value(
                  _i8.dummyValue<_i6.Either<_i7.Failure, _i6.Unit>>(
                    this,
                    Invocation.method(#signOut, []),
                  ),
                ),
          )
          as _i4.Future<_i6.Either<_i7.Failure, _i6.Unit>>);

  @override
  _i4.Stream<_i9.AppUser?> watchUser(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#watchUser, [uid]),
            returnValue: _i4.Stream<_i9.AppUser?>.empty(),
            returnValueForMissingStub: _i4.Stream<_i9.AppUser?>.empty(),
          )
          as _i4.Stream<_i9.AppUser?>);

  @override
  _i4.Future<_i6.Either<_i7.Failure, _i6.Unit>> updateUser(_i9.AppUser? user) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [user]),
            returnValue: _i4.Future<_i6.Either<_i7.Failure, _i6.Unit>>.value(
              _i8.dummyValue<_i6.Either<_i7.Failure, _i6.Unit>>(
                this,
                Invocation.method(#updateUser, [user]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i6.Either<_i7.Failure, _i6.Unit>>.value(
                  _i8.dummyValue<_i6.Either<_i7.Failure, _i6.Unit>>(
                    this,
                    Invocation.method(#updateUser, [user]),
                  ),
                ),
          )
          as _i4.Future<_i6.Either<_i7.Failure, _i6.Unit>>);

  @override
  _i4.Future<_i6.Either<_i7.Failure, _i6.Unit>> deleteAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, []),
            returnValue: _i4.Future<_i6.Either<_i7.Failure, _i6.Unit>>.value(
              _i8.dummyValue<_i6.Either<_i7.Failure, _i6.Unit>>(
                this,
                Invocation.method(#deleteAccount, []),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i6.Either<_i7.Failure, _i6.Unit>>.value(
                  _i8.dummyValue<_i6.Either<_i7.Failure, _i6.Unit>>(
                    this,
                    Invocation.method(#deleteAccount, []),
                  ),
                ),
          )
          as _i4.Future<_i6.Either<_i7.Failure, _i6.Unit>>);

  @override
  _i4.Future<_i6.Either<_i7.Failure, List<_i9.AppUser>>> getUsersByIds(
    List<String>? uids,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUsersByIds, [uids]),
            returnValue:
                _i4.Future<_i6.Either<_i7.Failure, List<_i9.AppUser>>>.value(
                  _i8.dummyValue<_i6.Either<_i7.Failure, List<_i9.AppUser>>>(
                    this,
                    Invocation.method(#getUsersByIds, [uids]),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i6.Either<_i7.Failure, List<_i9.AppUser>>>.value(
                  _i8.dummyValue<_i6.Either<_i7.Failure, List<_i9.AppUser>>>(
                    this,
                    Invocation.method(#getUsersByIds, [uids]),
                  ),
                ),
          )
          as _i4.Future<_i6.Either<_i7.Failure, List<_i9.AppUser>>>);

  @override
  _i4.Future<_i6.Either<_i7.Failure, _i6.Unit>> sendPasswordResetEmail(
    String? email,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [email]),
            returnValue: _i4.Future<_i6.Either<_i7.Failure, _i6.Unit>>.value(
              _i8.dummyValue<_i6.Either<_i7.Failure, _i6.Unit>>(
                this,
                Invocation.method(#sendPasswordResetEmail, [email]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i6.Either<_i7.Failure, _i6.Unit>>.value(
                  _i8.dummyValue<_i6.Either<_i7.Failure, _i6.Unit>>(
                    this,
                    Invocation.method(#sendPasswordResetEmail, [email]),
                  ),
                ),
          )
          as _i4.Future<_i6.Either<_i7.Failure, _i6.Unit>>);

  @override
  _i4.Future<_i6.Either<_i7.Failure, _i6.Unit>> sendEmailVerification() =>
      (super.noSuchMethod(
            Invocation.method(#sendEmailVerification, []),
            returnValue: _i4.Future<_i6.Either<_i7.Failure, _i6.Unit>>.value(
              _i8.dummyValue<_i6.Either<_i7.Failure, _i6.Unit>>(
                this,
                Invocation.method(#sendEmailVerification, []),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i6.Either<_i7.Failure, _i6.Unit>>.value(
                  _i8.dummyValue<_i6.Either<_i7.Failure, _i6.Unit>>(
                    this,
                    Invocation.method(#sendEmailVerification, []),
                  ),
                ),
          )
          as _i4.Future<_i6.Either<_i7.Failure, _i6.Unit>>);

  @override
  _i4.Future<bool> isEmailVerified() =>
      (super.noSuchMethod(
            Invocation.method(#isEmailVerified, []),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> reloadUser() =>
      (super.noSuchMethod(
            Invocation.method(#reloadUser, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [AnalyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsService extends _i1.Mock implements _i10.AnalyticsService {
  @override
  _i4.Future<void> logEvent({
    required String? name,
    Map<String, Object>? parameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logEvent, [], {
              #name: name,
              #parameters: parameters,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logScreenView({
    required String? screenName,
    String? screenClass,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logScreenView, [], {
              #screenName: screenName,
              #screenClass: screenClass,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setUserProperty({
    required String? name,
    required String? value,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setUserProperty, [], {
              #name: name,
              #value: value,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setUserId(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#setUserId, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i2.FirebaseAnalyticsObserver getObserver() =>
      (super.noSuchMethod(
            Invocation.method(#getObserver, []),
            returnValue: _FakeFirebaseAnalyticsObserver_0(
              this,
              Invocation.method(#getObserver, []),
            ),
            returnValueForMissingStub: _FakeFirebaseAnalyticsObserver_0(
              this,
              Invocation.method(#getObserver, []),
            ),
          )
          as _i2.FirebaseAnalyticsObserver);

  @override
  _i4.Future<void> logAuthSignupComplete({required String? method}) =>
      (super.noSuchMethod(
            Invocation.method(#logAuthSignupComplete, [], {#method: method}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logMatchPointFilter({
    required List<String>? instruments,
    required List<String>? genres,
    required double? distance,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logMatchPointFilter, [], {
              #instruments: instruments,
              #genres: genres,
              #distance: distance,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logFeedPostView({required String? postId}) =>
      (super.noSuchMethod(
            Invocation.method(#logFeedPostView, [], {#postId: postId}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logProfileEdit({required String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#logProfileEdit, [], {#userId: userId}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
