name: iOS Bug Report
description: Reportar bug encontrado em iPhone
title: "[iOS Bug] "
labels: ["bug", "ios"]
body:
  - type: markdown
    attributes:
      value: |
        Preencha os dados abaixo para reproduzir e corrigir rapido.
  - type: input
    id: ios_version
    attributes:
      label: iOS version
      placeholder: "ex: iOS 18.2"
    validations:
      required: true
  - type: input
    id: device
    attributes:
      label: Device model
      placeholder: "ex: iPhone 15 Pro"
    validations:
      required: true
  - type: input
    id: app_version
    attributes:
      label: App version/build
      placeholder: "ex: 1.0.3+27"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Liste os passos exatos para reproduzir o problema.
      placeholder: |
        1. Abrir tela X
        2. Tocar no botao Y
        3. Ver erro Z
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: evidence
    attributes:
      label: Logs / screenshot / video
      description: Cole logs do Xcode/Console e links de evidencia.
