// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBj0eL3neS7G6eCU0vN9CibAdtVat72EU',
    appId: '1:798301748829:web:f1b96526dcd3f99b47d7b4',
    messagingSenderId: '798301748829',
    projectId: 'mube-63a93',
    authDomain: 'mube-63a93.firebaseapp.com',
    storageBucket: 'mube-63a93.firebasestorage.app',
    measurementId: 'G-D56VW4HSY1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwaRJqkm5yuFCKbs5fMRTJyCMrYmbsRvU',
    appId: '1:798301748829:android:1b8aa37ebd4af6d847d7b4',
    messagingSenderId: '798301748829',
    projectId: 'mube-63a93',
    storageBucket: 'mube-63a93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtvjOvIDIVzdnIW1A9Piv4SuAXb3kw6CU',
    appId: '1:798301748829:ios:f87792294b0a913847d7b4',
    messagingSenderId: '798301748829',
    projectId: 'mube-63a93',
    storageBucket: 'mube-63a93.firebasestorage.app',
    iosBundleId: 'com.mube.mubeoficial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBj0eL3neS7G6eCU0vN9CibAdtVat72EU',
    appId: '1:798301748829:web:6a67c92e5d83b15347d7b4',
    messagingSenderId: '798301748829',
    projectId: 'mube-63a93',
    authDomain: 'mube-63a93.firebaseapp.com',
    storageBucket: 'mube-63a93.firebasestorage.app',
    measurementId: 'G-BE180JHHC0',
  );
}
