// Mocks generated by Mockito 5.4.6 from annotations
// in mube/test/unit/notifications/notification_providers_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:firebase_auth/firebase_auth.dart' as _i6;
import 'package:fpdart/fpdart.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:mube/src/core/errors/failures.dart' as _i8;
import 'package:mube/src/features/auth/data/auth_repository.dart' as _i5;
import 'package:mube/src/features/auth/domain/app_user.dart' as _i10;
import 'package:mube/src/features/notifications/data/notification_repository.dart'
    as _i2;
import 'package:mube/src/features/notifications/domain/notification_model.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [NotificationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationRepository extends _i1.Mock
    implements _i2.NotificationRepository {
  @override
  _i3.Stream<List<_i4.AppNotification>> watchNotifications(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#watchNotifications, [userId]),
            returnValue: _i3.Stream<List<_i4.AppNotification>>.empty(),
            returnValueForMissingStub:
                _i3.Stream<List<_i4.AppNotification>>.empty(),
          )
          as _i3.Stream<List<_i4.AppNotification>>);

  @override
  _i3.Future<void> markAsRead(String? userId, String? notificationId) =>
      (super.noSuchMethod(
            Invocation.method(#markAsRead, [userId, notificationId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> markAllAsRead(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#markAllAsRead, [userId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteNotification(String? userId, String? notificationId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNotification, [userId, notificationId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteAllNotifications(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllNotifications, [userId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i5.AuthRepository {
  @override
  bool get isCurrentUserEmailVerified =>
      (super.noSuchMethod(
            Invocation.getter(#isCurrentUserEmailVerified),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i3.Stream<_i6.User?> authStateChanges() =>
      (super.noSuchMethod(
            Invocation.method(#authStateChanges, []),
            returnValue: _i3.Stream<_i6.User?>.empty(),
            returnValueForMissingStub: _i3.Stream<_i6.User?>.empty(),
          )
          as _i3.Stream<_i6.User?>);

  @override
  _i3.Future<_i7.Either<_i8.Failure, _i7.Unit>> signInWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailAndPassword, [email, password]),
            returnValue: _i3.Future<_i7.Either<_i8.Failure, _i7.Unit>>.value(
              _i9.dummyValue<_i7.Either<_i8.Failure, _i7.Unit>>(
                this,
                Invocation.method(#signInWithEmailAndPassword, [
                  email,
                  password,
                ]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i7.Either<_i8.Failure, _i7.Unit>>.value(
                  _i9.dummyValue<_i7.Either<_i8.Failure, _i7.Unit>>(
                    this,
                    Invocation.method(#signInWithEmailAndPassword, [
                      email,
                      password,
                    ]),
                  ),
                ),
          )
          as _i3.Future<_i7.Either<_i8.Failure, _i7.Unit>>);

  @override
  _i3.Future<_i7.Either<_i8.Failure, _i7.Unit>> registerWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registerWithEmailAndPassword, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i3.Future<_i7.Either<_i8.Failure, _i7.Unit>>.value(
              _i9.dummyValue<_i7.Either<_i8.Failure, _i7.Unit>>(
                this,
                Invocation.method(#registerWithEmailAndPassword, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i7.Either<_i8.Failure, _i7.Unit>>.value(
                  _i9.dummyValue<_i7.Either<_i8.Failure, _i7.Unit>>(
                    this,
                    Invocation.method(#registerWithEmailAndPassword, [], {
                      #email: email,
                      #password: password,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i7.Either<_i8.Failure, _i7.Unit>>);

  @override
  _i3.Future<_i7.Either<_i8.Failure, _i7.Unit>> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i3.Future<_i7.Either<_i8.Failure, _i7.Unit>>.value(
              _i9.dummyValue<_i7.Either<_i8.Failure, _i7.Unit>>(
                this,
                Invocation.method(#signOut, []),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i7.Either<_i8.Failure, _i7.Unit>>.value(
                  _i9.dummyValue<_i7.Either<_i8.Failure, _i7.Unit>>(
                    this,
                    Invocation.method(#signOut, []),
                  ),
                ),
          )
          as _i3.Future<_i7.Either<_i8.Failure, _i7.Unit>>);

  @override
  _i3.Stream<_i10.AppUser?> watchUser(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#watchUser, [uid]),
            returnValue: _i3.Stream<_i10.AppUser?>.empty(),
            returnValueForMissingStub: _i3.Stream<_i10.AppUser?>.empty(),
          )
          as _i3.Stream<_i10.AppUser?>);

  @override
  _i3.Future<_i7.Either<_i8.Failure, _i7.Unit>> updateUser(
    _i10.AppUser? user,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [user]),
            returnValue: _i3.Future<_i7.Either<_i8.Failure, _i7.Unit>>.value(
              _i9.dummyValue<_i7.Either<_i8.Failure, _i7.Unit>>(
                this,
                Invocation.method(#updateUser, [user]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i7.Either<_i8.Failure, _i7.Unit>>.value(
                  _i9.dummyValue<_i7.Either<_i8.Failure, _i7.Unit>>(
                    this,
                    Invocation.method(#updateUser, [user]),
                  ),
                ),
          )
          as _i3.Future<_i7.Either<_i8.Failure, _i7.Unit>>);

  @override
  _i3.Future<_i7.Either<_i8.Failure, _i7.Unit>> deleteAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, []),
            returnValue: _i3.Future<_i7.Either<_i8.Failure, _i7.Unit>>.value(
              _i9.dummyValue<_i7.Either<_i8.Failure, _i7.Unit>>(
                this,
                Invocation.method(#deleteAccount, []),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i7.Either<_i8.Failure, _i7.Unit>>.value(
                  _i9.dummyValue<_i7.Either<_i8.Failure, _i7.Unit>>(
                    this,
                    Invocation.method(#deleteAccount, []),
                  ),
                ),
          )
          as _i3.Future<_i7.Either<_i8.Failure, _i7.Unit>>);

  @override
  _i3.Future<_i7.Either<_i8.Failure, List<_i10.AppUser>>> getUsersByIds(
    List<String>? uids,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUsersByIds, [uids]),
            returnValue:
                _i3.Future<_i7.Either<_i8.Failure, List<_i10.AppUser>>>.value(
                  _i9.dummyValue<_i7.Either<_i8.Failure, List<_i10.AppUser>>>(
                    this,
                    Invocation.method(#getUsersByIds, [uids]),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i7.Either<_i8.Failure, List<_i10.AppUser>>>.value(
                  _i9.dummyValue<_i7.Either<_i8.Failure, List<_i10.AppUser>>>(
                    this,
                    Invocation.method(#getUsersByIds, [uids]),
                  ),
                ),
          )
          as _i3.Future<_i7.Either<_i8.Failure, List<_i10.AppUser>>>);

  @override
  _i3.Future<_i7.Either<_i8.Failure, _i7.Unit>> sendPasswordResetEmail(
    String? email,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [email]),
            returnValue: _i3.Future<_i7.Either<_i8.Failure, _i7.Unit>>.value(
              _i9.dummyValue<_i7.Either<_i8.Failure, _i7.Unit>>(
                this,
                Invocation.method(#sendPasswordResetEmail, [email]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i7.Either<_i8.Failure, _i7.Unit>>.value(
                  _i9.dummyValue<_i7.Either<_i8.Failure, _i7.Unit>>(
                    this,
                    Invocation.method(#sendPasswordResetEmail, [email]),
                  ),
                ),
          )
          as _i3.Future<_i7.Either<_i8.Failure, _i7.Unit>>);

  @override
  _i3.Future<_i7.Either<_i8.Failure, _i7.Unit>> sendEmailVerification() =>
      (super.noSuchMethod(
            Invocation.method(#sendEmailVerification, []),
            returnValue: _i3.Future<_i7.Either<_i8.Failure, _i7.Unit>>.value(
              _i9.dummyValue<_i7.Either<_i8.Failure, _i7.Unit>>(
                this,
                Invocation.method(#sendEmailVerification, []),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i7.Either<_i8.Failure, _i7.Unit>>.value(
                  _i9.dummyValue<_i7.Either<_i8.Failure, _i7.Unit>>(
                    this,
                    Invocation.method(#sendEmailVerification, []),
                  ),
                ),
          )
          as _i3.Future<_i7.Either<_i8.Failure, _i7.Unit>>);

  @override
  _i3.Future<bool> isEmailVerified() =>
      (super.noSuchMethod(
            Invocation.method(#isEmailVerified, []),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> hasVerifiedEmailTokenClaim({bool? forceRefresh = false}) =>
      (super.noSuchMethod(
            Invocation.method(#hasVerifiedEmailTokenClaim, [], {
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> reloadUser() =>
      (super.noSuchMethod(
            Invocation.method(#reloadUser, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i7.Either<_i8.Failure, _i7.Unit>>
  ensureCurrentUserProfileExists() =>
      (super.noSuchMethod(
            Invocation.method(#ensureCurrentUserProfileExists, []),
            returnValue: _i3.Future<_i7.Either<_i8.Failure, _i7.Unit>>.value(
              _i9.dummyValue<_i7.Either<_i8.Failure, _i7.Unit>>(
                this,
                Invocation.method(#ensureCurrentUserProfileExists, []),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i7.Either<_i8.Failure, _i7.Unit>>.value(
                  _i9.dummyValue<_i7.Either<_i8.Failure, _i7.Unit>>(
                    this,
                    Invocation.method(#ensureCurrentUserProfileExists, []),
                  ),
                ),
          )
          as _i3.Future<_i7.Either<_i8.Failure, _i7.Unit>>);

  @override
  _i3.Future<_i7.Either<_i8.Failure, _i7.Unit>> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i3.Future<_i7.Either<_i8.Failure, _i7.Unit>>.value(
              _i9.dummyValue<_i7.Either<_i8.Failure, _i7.Unit>>(
                this,
                Invocation.method(#signInWithGoogle, []),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i7.Either<_i8.Failure, _i7.Unit>>.value(
                  _i9.dummyValue<_i7.Either<_i8.Failure, _i7.Unit>>(
                    this,
                    Invocation.method(#signInWithGoogle, []),
                  ),
                ),
          )
          as _i3.Future<_i7.Either<_i8.Failure, _i7.Unit>>);

  @override
  _i3.Future<_i7.Either<_i8.Failure, _i7.Unit>> signInWithApple() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithApple, []),
            returnValue: _i3.Future<_i7.Either<_i8.Failure, _i7.Unit>>.value(
              _i9.dummyValue<_i7.Either<_i8.Failure, _i7.Unit>>(
                this,
                Invocation.method(#signInWithApple, []),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i7.Either<_i8.Failure, _i7.Unit>>.value(
                  _i9.dummyValue<_i7.Either<_i8.Failure, _i7.Unit>>(
                    this,
                    Invocation.method(#signInWithApple, []),
                  ),
                ),
          )
          as _i3.Future<_i7.Either<_i8.Failure, _i7.Unit>>);
}
