// Mocks generated by Mockito 5.4.6 from annotations
// in mube/test/unit/features/feed/feed_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cloud_firestore/cloud_firestore.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:mube/src/features/feed/data/feed_remote_data_source.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeQuerySnapshot_0<T extends Object?> extends _i1.SmartFake
    implements _i2.QuerySnapshot<T> {
  _FakeQuerySnapshot_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDocumentSnapshot_1<T extends Object?> extends _i1.SmartFake
    implements _i2.DocumentSnapshot<T> {
  _FakeDocumentSnapshot_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSnapshotMetadata_2 extends _i1.SmartFake
    implements _i2.SnapshotMetadata {
  _FakeSnapshotMetadata_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDocumentReference_3<T1 extends Object?> extends _i1.SmartFake
    implements _i2.DocumentReference<T1> {
  _FakeDocumentReference_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FeedRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFeedRemoteDataSource extends _i1.Mock
    implements _i3.FeedRemoteDataSource {
  @override
  _i4.Future<_i2.QuerySnapshot<Map<String, dynamic>>> getNearbyUsers({
    required int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getNearbyUsers, [], {#limit: limit}),
            returnValue:
                _i4.Future<_i2.QuerySnapshot<Map<String, dynamic>>>.value(
                  _FakeQuerySnapshot_0<Map<String, dynamic>>(
                    this,
                    Invocation.method(#getNearbyUsers, [], {#limit: limit}),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i2.QuerySnapshot<Map<String, dynamic>>>.value(
                  _FakeQuerySnapshot_0<Map<String, dynamic>>(
                    this,
                    Invocation.method(#getNearbyUsers, [], {#limit: limit}),
                  ),
                ),
          )
          as _i4.Future<_i2.QuerySnapshot<Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.QuerySnapshot<Map<String, dynamic>>> getUsersByType({
    required String? type,
    required int? limit,
    _i2.DocumentSnapshot<Object?>? startAfter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUsersByType, [], {
              #type: type,
              #limit: limit,
              #startAfter: startAfter,
            }),
            returnValue:
                _i4.Future<_i2.QuerySnapshot<Map<String, dynamic>>>.value(
                  _FakeQuerySnapshot_0<Map<String, dynamic>>(
                    this,
                    Invocation.method(#getUsersByType, [], {
                      #type: type,
                      #limit: limit,
                      #startAfter: startAfter,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i2.QuerySnapshot<Map<String, dynamic>>>.value(
                  _FakeQuerySnapshot_0<Map<String, dynamic>>(
                    this,
                    Invocation.method(#getUsersByType, [], {
                      #type: type,
                      #limit: limit,
                      #startAfter: startAfter,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.QuerySnapshot<Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.QuerySnapshot<Map<String, dynamic>>> getUsersByCategory({
    required String? category,
    required int? limit,
    _i2.DocumentSnapshot<Object?>? startAfter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUsersByCategory, [], {
              #category: category,
              #limit: limit,
              #startAfter: startAfter,
            }),
            returnValue:
                _i4.Future<_i2.QuerySnapshot<Map<String, dynamic>>>.value(
                  _FakeQuerySnapshot_0<Map<String, dynamic>>(
                    this,
                    Invocation.method(#getUsersByCategory, [], {
                      #category: category,
                      #limit: limit,
                      #startAfter: startAfter,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i2.QuerySnapshot<Map<String, dynamic>>>.value(
                  _FakeQuerySnapshot_0<Map<String, dynamic>>(
                    this,
                    Invocation.method(#getUsersByCategory, [], {
                      #category: category,
                      #limit: limit,
                      #startAfter: startAfter,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.QuerySnapshot<Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.DocumentSnapshot<Map<String, dynamic>>> getUser(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [uid]),
            returnValue:
                _i4.Future<_i2.DocumentSnapshot<Map<String, dynamic>>>.value(
                  _FakeDocumentSnapshot_1<Map<String, dynamic>>(
                    this,
                    Invocation.method(#getUser, [uid]),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i2.DocumentSnapshot<Map<String, dynamic>>>.value(
                  _FakeDocumentSnapshot_1<Map<String, dynamic>>(
                    this,
                    Invocation.method(#getUser, [uid]),
                  ),
                ),
          )
          as _i4.Future<_i2.DocumentSnapshot<Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.QuerySnapshot<Map<String, dynamic>>> getGeohashNeighbors({
    required List<String>? neighbors,
    String? filterType,
    String? category,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getGeohashNeighbors, [], {
              #neighbors: neighbors,
              #filterType: filterType,
              #category: category,
            }),
            returnValue:
                _i4.Future<_i2.QuerySnapshot<Map<String, dynamic>>>.value(
                  _FakeQuerySnapshot_0<Map<String, dynamic>>(
                    this,
                    Invocation.method(#getGeohashNeighbors, [], {
                      #neighbors: neighbors,
                      #filterType: filterType,
                      #category: category,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i2.QuerySnapshot<Map<String, dynamic>>>.value(
                  _FakeQuerySnapshot_0<Map<String, dynamic>>(
                    this,
                    Invocation.method(#getGeohashNeighbors, [], {
                      #neighbors: neighbors,
                      #filterType: filterType,
                      #category: category,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.QuerySnapshot<Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.QuerySnapshot<Map<String, dynamic>>> getMainFeed({
    String? filterType,
    required int? limit,
    _i2.DocumentSnapshot<Object?>? startAfter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMainFeed, [], {
              #filterType: filterType,
              #limit: limit,
              #startAfter: startAfter,
            }),
            returnValue:
                _i4.Future<_i2.QuerySnapshot<Map<String, dynamic>>>.value(
                  _FakeQuerySnapshot_0<Map<String, dynamic>>(
                    this,
                    Invocation.method(#getMainFeed, [], {
                      #filterType: filterType,
                      #limit: limit,
                      #startAfter: startAfter,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i2.QuerySnapshot<Map<String, dynamic>>>.value(
                  _FakeQuerySnapshot_0<Map<String, dynamic>>(
                    this,
                    Invocation.method(#getMainFeed, [], {
                      #filterType: filterType,
                      #limit: limit,
                      #startAfter: startAfter,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.QuerySnapshot<Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.QuerySnapshot<Map<String, dynamic>>> getUsersByIds(
    List<String>? ids,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUsersByIds, [ids]),
            returnValue:
                _i4.Future<_i2.QuerySnapshot<Map<String, dynamic>>>.value(
                  _FakeQuerySnapshot_0<Map<String, dynamic>>(
                    this,
                    Invocation.method(#getUsersByIds, [ids]),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i2.QuerySnapshot<Map<String, dynamic>>>.value(
                  _FakeQuerySnapshot_0<Map<String, dynamic>>(
                    this,
                    Invocation.method(#getUsersByIds, [ids]),
                  ),
                ),
          )
          as _i4.Future<_i2.QuerySnapshot<Map<String, dynamic>>>);
}

/// A class which mocks [QuerySnapshot].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuerySnapshot<T extends Object?> extends _i1.Mock
    implements _i2.QuerySnapshot<T> {
  @override
  List<_i2.QueryDocumentSnapshot<T>> get docs =>
      (super.noSuchMethod(
            Invocation.getter(#docs),
            returnValue: <_i2.QueryDocumentSnapshot<T>>[],
            returnValueForMissingStub: <_i2.QueryDocumentSnapshot<T>>[],
          )
          as List<_i2.QueryDocumentSnapshot<T>>);

  @override
  List<_i2.DocumentChange<T>> get docChanges =>
      (super.noSuchMethod(
            Invocation.getter(#docChanges),
            returnValue: <_i2.DocumentChange<T>>[],
            returnValueForMissingStub: <_i2.DocumentChange<T>>[],
          )
          as List<_i2.DocumentChange<T>>);

  @override
  _i2.SnapshotMetadata get metadata =>
      (super.noSuchMethod(
            Invocation.getter(#metadata),
            returnValue: _FakeSnapshotMetadata_2(
              this,
              Invocation.getter(#metadata),
            ),
            returnValueForMissingStub: _FakeSnapshotMetadata_2(
              this,
              Invocation.getter(#metadata),
            ),
          )
          as _i2.SnapshotMetadata);

  @override
  int get size =>
      (super.noSuchMethod(
            Invocation.getter(#size),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);
}

/// A class which mocks [DocumentSnapshot].
///
/// See the documentation for Mockito's code generation for more information.
class MockDocumentSnapshot<T extends Object?> extends _i1.Mock
    implements _i2.DocumentSnapshot<T> {
  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i5.dummyValue<String>(this, Invocation.getter(#id)),
            returnValueForMissingStub: _i5.dummyValue<String>(
              this,
              Invocation.getter(#id),
            ),
          )
          as String);

  @override
  _i2.DocumentReference<T> get reference =>
      (super.noSuchMethod(
            Invocation.getter(#reference),
            returnValue: _FakeDocumentReference_3<T>(
              this,
              Invocation.getter(#reference),
            ),
            returnValueForMissingStub: _FakeDocumentReference_3<T>(
              this,
              Invocation.getter(#reference),
            ),
          )
          as _i2.DocumentReference<T>);

  @override
  _i2.SnapshotMetadata get metadata =>
      (super.noSuchMethod(
            Invocation.getter(#metadata),
            returnValue: _FakeSnapshotMetadata_2(
              this,
              Invocation.getter(#metadata),
            ),
            returnValueForMissingStub: _FakeSnapshotMetadata_2(
              this,
              Invocation.getter(#metadata),
            ),
          )
          as _i2.SnapshotMetadata);

  @override
  bool get exists =>
      (super.noSuchMethod(
            Invocation.getter(#exists),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  dynamic get(Object? field) => super.noSuchMethod(
    Invocation.method(#get, [field]),
    returnValueForMissingStub: null,
  );

  @override
  dynamic operator [](Object? field) => super.noSuchMethod(
    Invocation.method(#[], [field]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [QueryDocumentSnapshot].
///
/// See the documentation for Mockito's code generation for more information.
class MockQueryDocumentSnapshot<T extends Object?> extends _i1.Mock
    implements _i2.QueryDocumentSnapshot<T> {
  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i5.dummyValue<String>(this, Invocation.getter(#id)),
            returnValueForMissingStub: _i5.dummyValue<String>(
              this,
              Invocation.getter(#id),
            ),
          )
          as String);

  @override
  _i2.DocumentReference<T> get reference =>
      (super.noSuchMethod(
            Invocation.getter(#reference),
            returnValue: _FakeDocumentReference_3<T>(
              this,
              Invocation.getter(#reference),
            ),
            returnValueForMissingStub: _FakeDocumentReference_3<T>(
              this,
              Invocation.getter(#reference),
            ),
          )
          as _i2.DocumentReference<T>);

  @override
  _i2.SnapshotMetadata get metadata =>
      (super.noSuchMethod(
            Invocation.getter(#metadata),
            returnValue: _FakeSnapshotMetadata_2(
              this,
              Invocation.getter(#metadata),
            ),
            returnValueForMissingStub: _FakeSnapshotMetadata_2(
              this,
              Invocation.getter(#metadata),
            ),
          )
          as _i2.SnapshotMetadata);

  @override
  bool get exists =>
      (super.noSuchMethod(
            Invocation.getter(#exists),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  T data() =>
      (super.noSuchMethod(
            Invocation.method(#data, []),
            returnValue: _i5.dummyValue<T>(this, Invocation.method(#data, [])),
            returnValueForMissingStub: _i5.dummyValue<T>(
              this,
              Invocation.method(#data, []),
            ),
          )
          as T);

  @override
  dynamic get(Object? field) => super.noSuchMethod(
    Invocation.method(#get, [field]),
    returnValueForMissingStub: null,
  );

  @override
  dynamic operator [](Object? field) => super.noSuchMethod(
    Invocation.method(#[], [field]),
    returnValueForMissingStub: null,
  );
}
