// Mocks generated by Mockito 5.4.6 from annotations
// in mube/test/integration/profile/profile_flow_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i7;

import 'package:firebase_auth/firebase_auth.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:mube/src/features/auth/data/auth_remote_data_source.dart'
    as _i4;
import 'package:mube/src/features/auth/domain/app_user.dart' as _i6;
import 'package:mube/src/features/storage/data/storage_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserCredential_0 extends _i1.SmartFake
    implements _i2.UserCredential {
  _FakeUserCredential_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeImageUrls_1 extends _i1.SmartFake implements _i3.ImageUrls {
  _FakeImageUrls_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGalleryMediaUrls_2 extends _i1.SmartFake
    implements _i3.GalleryMediaUrls {
  _FakeGalleryMediaUrls_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i4.AuthRemoteDataSource {
  @override
  _i5.Stream<_i2.User?> authStateChanges() =>
      (super.noSuchMethod(
            Invocation.method(#authStateChanges, []),
            returnValue: _i5.Stream<_i2.User?>.empty(),
            returnValueForMissingStub: _i5.Stream<_i2.User?>.empty(),
          )
          as _i5.Stream<_i2.User?>);

  @override
  _i5.Future<void> signInWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailAndPassword, [email, password]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.User?> registerWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#registerWithEmailAndPassword, [email, password]),
            returnValue: _i5.Future<_i2.User?>.value(),
            returnValueForMissingStub: _i5.Future<_i2.User?>.value(),
          )
          as _i5.Future<_i2.User?>);

  @override
  _i5.Future<_i2.UserCredential> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i5.Future<_i2.UserCredential>.value(
              _FakeUserCredential_0(
                this,
                Invocation.method(#signInWithGoogle, []),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.UserCredential>.value(
              _FakeUserCredential_0(
                this,
                Invocation.method(#signInWithGoogle, []),
              ),
            ),
          )
          as _i5.Future<_i2.UserCredential>);

  @override
  _i5.Future<_i2.UserCredential> signInWithApple() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithApple, []),
            returnValue: _i5.Future<_i2.UserCredential>.value(
              _FakeUserCredential_0(
                this,
                Invocation.method(#signInWithApple, []),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.UserCredential>.value(
              _FakeUserCredential_0(
                this,
                Invocation.method(#signInWithApple, []),
              ),
            ),
          )
          as _i5.Future<_i2.UserCredential>);

  @override
  _i5.Future<void> saveUserProfile(_i6.AppUser? user) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserProfile, [user]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateUserProfile(_i6.AppUser? user) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfile, [user]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i6.AppUser?> fetchUserProfile(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUserProfile, [uid]),
            returnValue: _i5.Future<_i6.AppUser?>.value(),
            returnValueForMissingStub: _i5.Future<_i6.AppUser?>.value(),
          )
          as _i5.Future<_i6.AppUser?>);

  @override
  _i5.Stream<_i6.AppUser?> watchUserProfile(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#watchUserProfile, [uid]),
            returnValue: _i5.Stream<_i6.AppUser?>.empty(),
            returnValueForMissingStub: _i5.Stream<_i6.AppUser?>.empty(),
          )
          as _i5.Stream<_i6.AppUser?>);

  @override
  _i5.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteAccount(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, [uid]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i6.AppUser>> fetchUsersByIds(List<String>? uids) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUsersByIds, [uids]),
            returnValue: _i5.Future<List<_i6.AppUser>>.value(<_i6.AppUser>[]),
            returnValueForMissingStub: _i5.Future<List<_i6.AppUser>>.value(
              <_i6.AppUser>[],
            ),
          )
          as _i5.Future<List<_i6.AppUser>>);

  @override
  _i5.Future<void> sendPasswordResetEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [email]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> sendEmailVerification() =>
      (super.noSuchMethod(
            Invocation.method(#sendEmailVerification, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> isEmailVerified() =>
      (super.noSuchMethod(
            Invocation.method(#isEmailVerified, []),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> reloadUser() =>
      (super.noSuchMethod(
            Invocation.method(#reloadUser, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [StorageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageRepository extends _i1.Mock implements _i3.StorageRepository {
  @override
  _i5.Future<_i3.ImageUrls> uploadProfileImageWithSizes({
    required String? userId,
    required _i7.File? file,
    bool? generateMultipleSizes = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadProfileImageWithSizes, [], {
              #userId: userId,
              #file: file,
              #generateMultipleSizes: generateMultipleSizes,
            }),
            returnValue: _i5.Future<_i3.ImageUrls>.value(
              _FakeImageUrls_1(
                this,
                Invocation.method(#uploadProfileImageWithSizes, [], {
                  #userId: userId,
                  #file: file,
                  #generateMultipleSizes: generateMultipleSizes,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.ImageUrls>.value(
              _FakeImageUrls_1(
                this,
                Invocation.method(#uploadProfileImageWithSizes, [], {
                  #userId: userId,
                  #file: file,
                  #generateMultipleSizes: generateMultipleSizes,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.ImageUrls>);

  @override
  _i5.Future<String> uploadProfileImage({
    required String? userId,
    required _i7.File? file,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadProfileImage, [], {
              #userId: userId,
              #file: file,
            }),
            returnValue: _i5.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#uploadProfileImage, [], {
                  #userId: userId,
                  #file: file,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#uploadProfileImage, [], {
                  #userId: userId,
                  #file: file,
                }),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<_i3.GalleryMediaUrls> uploadGalleryMediaWithSizes({
    required String? userId,
    required _i7.File? file,
    required String? mediaId,
    required bool? isVideo,
    void Function(double)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadGalleryMediaWithSizes, [], {
              #userId: userId,
              #file: file,
              #mediaId: mediaId,
              #isVideo: isVideo,
              #onProgress: onProgress,
            }),
            returnValue: _i5.Future<_i3.GalleryMediaUrls>.value(
              _FakeGalleryMediaUrls_2(
                this,
                Invocation.method(#uploadGalleryMediaWithSizes, [], {
                  #userId: userId,
                  #file: file,
                  #mediaId: mediaId,
                  #isVideo: isVideo,
                  #onProgress: onProgress,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.GalleryMediaUrls>.value(
              _FakeGalleryMediaUrls_2(
                this,
                Invocation.method(#uploadGalleryMediaWithSizes, [], {
                  #userId: userId,
                  #file: file,
                  #mediaId: mediaId,
                  #isVideo: isVideo,
                  #onProgress: onProgress,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.GalleryMediaUrls>);

  @override
  _i5.Future<String> uploadGalleryMedia({
    required String? userId,
    required _i7.File? file,
    required String? mediaId,
    required bool? isVideo,
    void Function(double)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadGalleryMedia, [], {
              #userId: userId,
              #file: file,
              #mediaId: mediaId,
              #isVideo: isVideo,
              #onProgress: onProgress,
            }),
            returnValue: _i5.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#uploadGalleryMedia, [], {
                  #userId: userId,
                  #file: file,
                  #mediaId: mediaId,
                  #isVideo: isVideo,
                  #onProgress: onProgress,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#uploadGalleryMedia, [], {
                  #userId: userId,
                  #file: file,
                  #mediaId: mediaId,
                  #isVideo: isVideo,
                  #onProgress: onProgress,
                }),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<String> uploadVideoThumbnail({
    required String? userId,
    required String? mediaId,
    required _i7.File? thumbnail,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadVideoThumbnail, [], {
              #userId: userId,
              #mediaId: mediaId,
              #thumbnail: thumbnail,
            }),
            returnValue: _i5.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#uploadVideoThumbnail, [], {
                  #userId: userId,
                  #mediaId: mediaId,
                  #thumbnail: thumbnail,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#uploadVideoThumbnail, [], {
                  #userId: userId,
                  #mediaId: mediaId,
                  #thumbnail: thumbnail,
                }),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<void> deleteImage(String? imageUrl) =>
      (super.noSuchMethod(
            Invocation.method(#deleteImage, [imageUrl]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteGalleryItem({
    required String? userId,
    required String? mediaId,
    required bool? isVideo,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteGalleryItem, [], {
              #userId: userId,
              #mediaId: mediaId,
              #isVideo: isVideo,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteProfileImages(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProfileImages, [userId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String> uploadSupportAttachment({
    required String? ticketId,
    required _i7.File? file,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadSupportAttachment, [], {
              #ticketId: ticketId,
              #file: file,
            }),
            returnValue: _i5.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#uploadSupportAttachment, [], {
                  #ticketId: ticketId,
                  #file: file,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#uploadSupportAttachment, [], {
                  #ticketId: ticketId,
                  #file: file,
                }),
              ),
            ),
          )
          as _i5.Future<String>);
}
